# Rancangan Sistem

Rancangan awal, sistem ini digunakan untuk menganalisis penjualan dengan periode bulanan dalam satu tahun.

# Preprocessing Data

In [ ]:
# Upload dataset
from google.colab import files
files.upload()

Saving Dataset_sales.csv to Dataset_sales (2).csv

{'Dataset_sales (2).csv': b'Transaction_ID,Date,Product_Name,Category,Units_Sold,Unit_Price,Total_Revenue,Store_Location,Payment_Method\nT0001,2024-10-06,Pepsodent Toothpaste,Personal Care,N/A,15000,675000.0,Jakarta,Cash\nT0002,2024-10-01,ABC Kecap Manis 620ml,Groceries,60,18000,1080000.0,Jakarta,Card\nT0003,2024-10-01,Lifebuoy Body Wash,Personal Care,17,25000,425000.0,Medan,Cash\nT0004,2024-10-06,Milo 1kg,Drinks,95,90000,8550000.0,Bandung,Cash\nT0005,2024-10-03,Indomie Goreng,Instant Noodles,30,3000,90000.0,Surabaya,Card\nT0006,2024-10-02,Sari Roti Tawar,Snacks,25,12000,300000.0,Jakarta,Card\nT0007,2024-10-02,SilverQueen Milk Chocolate,Snacks,43,12000,516000.0,Jakarta,Card\nT0008,2024-10-02,Nabati Wafer,Snacks,82,5000,410000.0,Bandung,Card\nT0009,2024-10-06,Rexona Deodorant,Personal Care,39,20000,780000.0,Jakarta,Cash\nT0010,2024-10-01,Aqua 600ml,Drinks,70,4000,280000.0,Bandung,Cash\nT0011,2024-10-06,Sampoerna Mild 16,Smokes,93,30000,2790000.0,Surabaya,Cash\nT0012,2024-10-06,Sari Roti Tawar,Snacks,19,12000,228000.0,Jakarta,Cash\nT0013,2024-10-05,Aqua 600ml,Drinks,61,4000,244000.0,Medan,Card\nT0014,2024-10-01,SilverQueen Milk Chocolate,Snacks,80,12000,960000.0,Surabaya,Cash\nT0015,2024-10-05,Sedaap Soto,Instant Noodles,41,2800,114800.0,Medan,Cash\nT0016,2024-10-04,Lifebuoy Body Wash,Personal Care,29,25000,,Medan,Cash\nT0017,2024-10-01,Indomie Goreng,Instant Noodles,52,3000,,Medan,Card\nT0018,2024-10-01,Lifebuoy Body Wash,Personal Care,63,25000,1575000.0,Jakarta,Cash\nT0019,2024-10-01,Lifebuoy Body Wash,Personal Care,N/A,25000,1900000.0,Surabaya,Card\nT0020,2024-10-02,Rexona Deodorant,Personal Care,74,20000,1480000.0,Medan,Cash\nT0021,2024-10-02,Pepsodent Toothpaste,Personal Care,40,15000,600000.0,Surabaya,Card\nT0022,2024-10-05,ABC Kecap Manis 620ml,Groceries,67,18000,1206000.0,Jakarta,Cash\nT0023,2024-10-05,Rexona Deodorant,Personal Care,29,20000,580000.0,Medan,Card\nT0024,2024-10-01,Pocari Sweat 500ml,Drinks,36,7500,270000.0,Medan,Card\nT0025,2024-10-05,Milo 1kg,Drinks,100,90000,9000000.0,Jakarta,Cash\nT0026,2024-10-02,SilverQueen Milk Chocolate,Snacks,41,12000,492000.0,Medan,Cash\nT0027,2024-10-06,Tolak Angin,Health,13,7000,91000.0,Medan,Cash\nT0028,2024-10-06,Pepsodent Toothpaste,Personal Care,25,15000,,Bandung,Cash\nT0029,2024-10-06,SilverQueen Milk Chocolate,Snacks,N/A,12000,1008000.0,Jakarta,Cash\nT0030,2024-10-05,Tolako Minuman Herbal,Health,26,8500,221000.0,Surabaya,Cash\nT0031,2024-10-04,Tolak Angin,Health,83,7000,581000.0,Medan,Card\nT0032,2024-10-02,Tolak Angin,Health,55,7000,385000.0,Bandung,Card\nT0033,2024-10-04,Aqua 600ml,Drinks,88,4000,352000.0,Bandung,Card\nT0034,2024-10-05,Nabati Wafer,Snacks,17,5000,85000.0,Medan,Cash\nT0035,2024-10-03,Indomilk UHT 1L,Drinks,41,15000,615000.0,Jakarta,Card\nT0036,2024-10-01,Sampoerna Mild 16,Smokes,72,30000,2160000.0,Surabaya,Card\nT0037,2024-10-02,Sedaap Soto,Instant Noodles,38,2800,,Surabaya,Cash\nT0038,2024-10-06,Pocari Sweat 500ml,Drinks,84,7500,630000.0,Bandung,Cash\nT0039,2024-10-04,Sampoerna Mild 16,Smokes,17,30000,510000.0,Bandung,Card\nT0040,2024-10-03,Tolak Angin,Health,32,7000,224000.0,Surabaya,Card\nT0041,2024-10-03,Pocari Sweat 500ml,Drinks,82,7500,615000.0,Bandung,Card\nT0042,2024-10-02,Aqua 600ml,Drinks,21,4000,84000.0,Bandung,Cash\nT0043,2024-10-02,Sedaap Soto,Instant Noodles,35,2800,98000.0,Surabaya,Cash\nT0044,2024-10-03,ABC Kecap Manis 620ml,Groceries,17,18000,,Bandung,Cash\nT0045,2024-10-01,SilverQueen Milk Chocolate,Snacks,57,12000,684000.0,Medan,Cash\nT0046,2024-10-01,Tolak Angin,Health,65,7000,455000.0,Medan,Card\nT0047,2024-10-04,Sedaap Soto,Instant Noodles,55,2800,154000.0,Bandung,Card\nT0048,2024-10-01,Pepsodent Toothpaste,Personal Care,32,15000,480000.0,Medan,Cash\nT0049,2024-10-03,Sedaap Soto,Instant Noodles,38,2800,106400.0,Jakarta,Card\nT0050,2024-10-03,Lifebuoy Body Wash,Personal Care,54,25000,1350000.0,Bandung,Cash\nT0051,2024-10-05,ABC Kecap Manis 620ml,Groceries,67,18000,,Bandung,Cash\nT0052,2024-10-03,Rexona Deodorant,Personal Care,10,20000,,Medan,Card\nT0053,2024-10-01,Nabati Wafer,Snacks,58,5000,290000.0,Medan,Cash\nT0054,2024-10-06,Pantene Shampoo 1L,Personal Care,93,45000,4185000.0,Bandung,Cash\nT0055,2024-10-04,Aqua 600ml,Drinks,47,4000,,Surabaya,Cash\nT0056,2024-10-05,Frisian Flag Susu Kental Manis,Groceries,30,10000,300000.0,Jakarta,Card\nT0057,2024-10-01,Nabati Wafer,Snacks,100,5000,,Bandung,Card\nT0058,2024-10-04,Beras Maknyuss 5kg,Groceries,34,65000,2210000.0,Surabaya,Card\nT0059,2024-10-01,Frisian Flag Susu Kental Manis,Groceries,83,10000,830000.0,Medan,Cash\nT0060,2024-10-05,SilverQueen Milk Chocolate,Snacks,47,12000,564000.0,Medan,Cash\nT0061,2024-10-03,Milo 1kg,Drinks,20,90000,1800000.0,Jakarta,Card\nT0062,2024-10-06,Sari Roti Tawar,Snacks,21,12000,252000.0,Medan,Cash\nT0063,2024-10-05,Tolak Angin,Health,67,7000,,Medan,Card\nT0064,2024-10-03,Pantene Shampoo 1L,Personal Care,17,45000,765000.0,Jakarta,Cash\nT0065,2024-10-05,Bimoli Minyak Goreng 2L,Groceries,85,33000,2805000.0,Jakarta,Card\nT0066,2024-10-02,Sampoerna Mild 16,Smokes,97,30000,2910000.0,Medan,Cash\nT0067,2024-10-06,Aqua 600ml,Drinks,74,4000,296000.0,Bandung,Cash\nT0068,2024-10-01,Tolak Angin,Health,37,error,259000.0,Bandung,Cash\nT0069,2024-10-01,Bimoli Minyak Goreng 2L,Groceries,35,33000,1155000.0,Bandung,Card\nT0070,2024-10-06,SilverQueen Milk Chocolate,Snacks,21,12000,252000.0,Medan,Card\nT0071,2024-10-02,Indomie Goreng,Instant Noodles,99,3000,297000.0,Medan,Cash\nT0072,2024-10-03,Pantene Shampoo 1L,Personal Care,84,45000,3780000.0,Jakarta,Cash\nT0073,2024-10-01,Milo 1kg,Drinks,78,90000,7020000.0,Medan,Card\nT0074,2024-10-02,Sedaap Soto,Instant Noodles,70,2800,,Surabaya,Card\nT0075,2024-10-01,Frisian Flag Susu Kental Manis,Groceries,14,10000,140000.0,Surabaya,Cash\nT0076,2024-10-04,Sari Roti Tawar,Snacks,57,12000,,Surabaya,Card\nT0077,2024-10-03,Rexona Deodorant,Personal Care,39,20000,780000.0,Medan,Card\nT0078,2024-10-04,SilverQueen Milk Chocolate,Snacks,34,12000,408000.0,Medan,Card\nT0079,2024-10-06,Aqua 600ml,Drinks,75,4000,300000.0,Jakarta,Card\nT0080,2024-10-03,Indomilk UHT 1L,Drinks,82,15000,,Bandung,Cash\nT0081,2024-10-02,Tolako Minuman Herbal,Health,16,8500,136000.0,Bandung,Card\nT0082,2024-10-03,Frisian Flag Susu Kental Manis,Groceries,91,10000,910000.0,Jakarta,Cash\nT0083,2024-10-03,Tolak Angin,Health,70,7000,490000.0,Surabaya,Card\nT0084,2024-10-02,SilverQueen Milk Chocolate,Snacks,46,12000,,Jakarta,Cash\nT0085,2024-10-06,Beras Maknyuss 5kg,Groceries,38,65000,2470000.0,Bandung,Card\nT0086,2024-10-03,Indomie Goreng,Instant Noodles,70,3000,210000.0,Bandung,Cash\nT0087,2024-10-06,Milo 1kg,Drinks,100,90000,9000000.0,Medan,Card\nT0088,2024-10-06,Beras Maknyuss 5kg,Groceries,69,error,4485000.0,Medan,Cash\nT0089,2024-10-06,Pocari Sweat 500ml,Drinks,81,7500,607500.0,Surabaya,Card\nT0090,2024-10-01,ABC Kecap Manis 620ml,Groceries,45,18000,810000.0,Surabaya,Card\nT0091,2024-10-05,Milo 1kg,Drinks,34,90000,3060000.0,Bandung,Cash\nT0092,2024-10-06,Sedaap Soto,Instant Noodles,61,error,170800.0,Bandung,Cash\nT0093,2024-10-02,Sari Roti Tawar,Snacks,63,12000,756000.0,Jakarta,Cash\nT0094,2024-10-05,Sampoerna Mild 16,Smokes,91,30000,2730000.0,Surabaya,Card\nT0095,2024-10-06,Sampoerna Mild 16,Smokes,33,30000,990000.0,Medan,Cash\nT0096,2024-10-02,Sampoerna Mild 16,Smokes,33,30000,990000.0,Surabaya,Cash\nT0097,2024-10-02,Milo 1kg,Drinks,63,90000,5670000.0,Surabaya,Card\nT0098,2024-10-04,Rexona Deodorant,Personal Care,70,20000,1400000.0,Jakarta,Card\nT0099,2024-10-04,Frisian Flag Susu Kental Manis,Groceries,77,10000,770000.0,Jakarta,Cash\nT0100,2024-10-03,Bimoli Minyak Goreng 2L,Groceries,82,33000,2706000.0,Medan,Cash\nT0101,2024-10-06,SilverQueen Milk Chocolate,Snacks,72,12000,864000.0,Bandung,Card\nT0102,2024-10-06,Sari Roti Tawar,Snacks,36,12000,432000.0,Bandung,Cash\nT0103,2024-10-05,SilverQueen Milk Chocolate,Snacks,26,12000,312000.0,Medan,Card\nT0104,2024-10-02,Indomie Goreng,Instant Noodles,14,3000,42000.0,Surabaya,Cash\nT0105,2024-10-06,Indomilk UHT 1L,Drinks,34,15000,,Jakarta,Cash\nT0106,2024-10-03,Milo 1kg,Drinks,26,90000,2340000.0,Surabaya,Cash\nT0107,2024-10-01,Milo 1kg,Drinks,68,error,6120000.0,Surabaya,Card\nT0108,2024-10-02,ABC Kecap Manis 620ml,Groceries,72,18000,1296000.0,Bandung,Cash\nT0109,2024-10-01,Frisian Flag Susu Kental Manis,Groceries,12,10000,120000.0,Bandung,Cash\nT0110,2024-10-03,Tolak Angin,Health,25,7000,175000.0,Jakarta,Card\nT0111,2024-10-04,Sampoerna Mild 16,Smokes,89,30000,,Jakarta,Cash\nT0112,2024-10-03,Rexona Deodorant,Personal Care,63,20000,1260000.0,Jakarta,Card\nT0113,2024-10-01,Indomie Goreng,Instant Noodles,48,3000,144000.0,Jakarta,Card\nT0114,2024-10-02,Bimoli Minyak Goreng 2L,Groceries,23,33000,759000.0,Jakarta,Card\nT0115,2024-10-05,Beras Maknyuss 5kg,Groceries,87,65000,5655000.0,Surabaya,Cash\nT0116,2024-10-06,Tolak Angin,Health,15,7000,105000.0,Bandung,Card\nT0117,2024-10-03,SilverQueen Milk Chocolate,Snacks,24,12000,288000.0,Medan,Cash\nT0118,2024-10-02,SilverQueen Milk Chocolate,Snacks,N/A,12000,264000.0,Bandung,Card\nT0119,2024-10-06,Tolako Minuman Herbal,Health,16,8500,136000.0,Bandung,Cash\nT0120,2024-10-04,ABC Kecap Manis 620ml,Groceries,64,18000,1152000.0,Jakarta,Cash\nT0121,2024-10-04,Tolak Angin,Health,52,7000,364000.0,Medan,Card\nT0122,2024-10-06,ABC Kecap Manis 620ml,Groceries,33,18000,594000.0,Medan,Card\nT0123,2024-10-04,Nabati Wafer,Snacks,63,5000,315000.0,Bandung,Cash\nT0124,2024-10-02,Tolak Angin,Health,23,7000,161000.0,Medan,Card\nT0125,2024-10-03,Pocari Sweat 500ml,Drinks,88,7500,,Bandung,Card\nT0126,2024-10-02,Bimoli Minyak Goreng 2L,Groceries,66,33000,,Surabaya,Card\nT0127,2024-10-02,Indomilk UHT 1L,Drinks,83,15000,1245000.0,Bandung,Card\nT0128,2024-10-06,Sedaap Soto,Instant Noodles,22,2800,61600.0,Bandung,Card\nT0129,2024-10-05,Frisian Flag Susu Kental Manis,Groceries,29,10000,290000.0,Jakarta,Cash\nT0130,2024-10-05,Nabati Wafer,Snacks,73,5000,365000.0,Jakarta,Card\nT0131,2024-10-03,Sari Roti Tawar,Snacks,16,12000,192000.0,Medan,Card\nT0132,2024-10-06,Tolako Minuman Herbal,Health,83,error,705500.0,Medan,Card\nT0133,2024-10-05,Indomie Goreng,Instant Noodles,23,3000,69000.0,Jakarta,Cash\nT0134,2024-10-04,Sedaap Soto,Instant Noodles,91,2800,254800.0,Bandung,Card\nT0135,2024-10-05,Aqua 600ml,Drinks,38,4000,152000.0,Surabaya,Card\nT0136,2024-10-04,Tolako Minuman Herbal,Health,24,8500,204000.0,Bandung,Cash\nT0137,2024-10-03,Milo 1kg,Drinks,80,90000,7200000.0,Jakarta,Cash\nT0138,2024-10-02,Bimoli Minyak Goreng 2L,Groceries,23,33000,759000.0,Bandung,Cash\nT0139,2024-10-02,Beras Maknyuss 5kg,Groceries,68,65000,4420000.0,Bandung,Card\nT0140,2024-10-05,Pantene Shampoo 1L,Personal Care,25,45000,1125000.0,Medan,Card\nT0141,2024-10-04,Pepsodent Toothpaste,Personal Care,73,15000,,Jakarta,Card\nT0142,2024-10-01,Indomilk UHT 1L,Drinks,32,15000,480000.0,Bandung,Cash\nT0143,2024-10-01,Sedaap Soto,Instant Noodles,N/A,2800,142800.0,Medan,Card\nT0144,2024-10-01,Lifebuoy Body Wash,Personal Care,45,25000,1125000.0,Surabaya,Card\nT0145,2024-10-02,Bimoli Minyak Goreng 2L,Groceries,87,33000,2871000.0,Surabaya,Card\nT0146,2024-10-06,Beras Maknyuss 5kg,Groceries,35,65000,2275000.0,Surabaya,Card\nT0147,2024-10-02,Tolak Angin,Health,74,7000,518000.0,Surabaya,Cash\nT0148,2024-10-06,Pantene Shampoo 1L,Personal Care,83,45000,3735000.0,Medan,Card\nT0149,2024-10-04,Indomie Goreng,Instant Noodles,76,3000,228000.0,Medan,Cash\nT0150,2024-10-05,Sari Roti Tawar,Snacks,30,12000,360000.0,Surabaya,Cash\nT0151,2024-10-01,Milo 1kg,Drinks,36,90000,3240000.0,Jakarta,Card\nT0152,2024-10-04,Sampoerna Mild 16,Smokes,38,30000,1140000.0,Medan,Cash\nT0153,2024-10-04,Milo 1kg,Drinks,98,90000,8820000.0,Medan,Card\nT0154,2024-10-05,ABC Kecap Manis 620ml,Groceries,80,18000,1440000.0,Surabaya,Cash\nT0155,2024-10-04,Tolako Minuman Herbal,Health,38,8500,323000.0,Surabaya,Cash\nT0156,2024-10-05,Milo 1kg,Drinks,67,90000,6030000.0,Jakarta,Cash\nT0157,2024-10-03,Rexona Deodorant,Personal Care,58,20000,,Surabaya,Card\nT0158,2024-10-05,Sari Roti Tawar,Snacks,10,12000,120000.0,Bandung,Cash\nT0159,2024-10-01,Aqua 600ml,Drinks,90,4000,360000.0,Surabaya,Card\nT0160,2024-10-06,SilverQueen Milk Chocolate,Snacks,100,12000,1200000.0,Bandung,Cash\nT0161,2024-10-06,Tolak Angin,Health,63,7000,441000.0,Medan,Cash\nT0162,2024-10-01,ABC Kecap Manis 620ml,Groceries,N/A,18000,936000.0,Bandung,Card\nT0163,2024-10-06,Indomie Goreng,Instant Noodles,24,3000,72000.0,Medan,Cash\nT0164,2024-10-05,Sedaap Soto,Instant Noodles,41,2800,114800.0,Surabaya,Card\nT0165,2024-10-03,Frisian Flag Susu Kental Manis,Groceries,42,10000,420000.0,Surabaya,Cash\nT0166,2024-10-06,Pocari Sweat 500ml,Drinks,75,7500,562500.0,Medan,Card\nT0167,2024-10-03,Beras Maknyuss 5kg,Groceries,N/A,65000,3315000.0,Jakarta,Cash\nT0168,2024-10-01,Sampoerna Mild 16,Smokes,10,30000,300000.0,Bandung,Cash\nT0169,2024-10-03,Rexona Deodorant,Personal Care,36,20000,720000.0,Medan,Cash\nT0170,2024-10-04,Tolako Minuman Herbal,Health,52,8500,,Jakarta,Cash\nT0171,2024-10-02,SilverQueen Milk Chocolate,Snacks,83,12000,996000.0,Surabaya,Card\nT0172,2024-10-04,Bimoli Minyak Goreng 2L,Groceries,50,33000,,Jakarta,Cash\nT0173,2024-10-01,Pantene Shampoo 1L,Personal Care,15,45000,675000.0,Jakarta,Card\nT0174,2024-10-06,Milo 1kg,Drinks,87,90000,7830000.0,Medan,Card\nT0175,2024-10-06,Nabati Wafer,Snacks,30,5000,150000.0,Bandung,Card\nT0176,2024-10-03,Milo 1kg,Drinks,91,90000,8190000.0,Surabaya,Cash\nT0177,2024-10-05,Rexona Deodorant,Personal Care,15,20000,,Medan,Cash\nT0178,2024-10-02,Pocari Sweat 500ml,Drinks,37,7500,277500.0,Bandung,Cash\nT0179,2024-10-05,Sari Roti Tawar,Snacks,34,12000,408000.0,Jakarta,Card\nT0180,2024-10-01,SilverQueen Milk Chocolate,Snacks,42,12000,504000.0,Medan,Card\nT0181,2024-10-06,Lifebuoy Body Wash,Personal Care,22,25000,550000.0,Jakarta,Cash\nT0182,2024-10-03,Sedaap Soto,Instant Noodles,94,2800,263200.0,Bandung,Card\nT0183,2024-10-06,Tolak Angin,Health,10,7000,70000.0,Bandung,Card\nT0184,2024-10-05,ABC Kecap Manis 620ml,Groceries,71,18000,1278000.0,Surabaya,Card\nT0185,2024-10-05,Sedaap Soto,Instant Noodles,20,2800,56000.0,Bandung,Cash\nT0186,2024-10-02,SilverQueen Milk Chocolate,Snacks,19,12000,228000.0,Jakarta,Card\nT0187,2024-10-02,Aqua 600ml,Drinks,80,4000,320000.0,Medan,Cash\nT0188,2024-10-03,Pantene Shampoo 1L,Personal Care,47,45000,2115000.0,Jakarta,Card\nT0189,2024-10-02,Lifebuoy Body Wash,Personal Care,88,25000,2200000.0,Bandung,Card\nT0190,2024-10-05,Pantene Shampoo 1L,Personal Care,94,45000,4230000.0,Bandung,Card\nT0191,2024-10-05,Nabati Wafer,Snacks,39,5000,195000.0,Surabaya,Cash\nT0192,2024-10-01,Pocari Sweat 500ml,Drinks,59,7500,442500.0,Medan,Cash\nT0193,2024-10-05,Rexona Deodorant,Personal Care,100,20000,2000000.0,Surabaya,Card\nT0194,2024-10-03,Frisian Flag Susu Kental Manis,Groceries,93,10000,930000.0,Jakarta,Card\nT0195,2024-10-04,Indomilk UHT 1L,Drinks,61,15000,915000.0,Surabaya,Card\nT0196,2024-10-01,Indomie Goreng,Instant Noodles,74,3000,222000.0,Medan,Cash\nT0197,2024-10-01,Sari Roti Tawar,Snacks,37,12000,444000.0,Bandung,Card\nT0198,2024-10-03,Lifebuoy Body Wash,Personal Care,63,25000,1575000.0,Jakarta,Card\nT0199,2024-10-03,Pantene Shampoo 1L,Personal Care,30,45000,1350000.0,Medan,Cash\nT0200,2024-10-02,Pantene Shampoo 1L,Personal Care,30,45000,1350000.0,Jakarta,Cash\nT0201,2024-10-01,Tolak Angin,Health,76,7000,532000.0,Jakarta,Card\nT0202,2024-10-02,Sedaap Soto,Instant Noodles,70,2800,196000.0,Bandung,Cash\nT0203,2024-10-05,Pantene Shampoo 1L,Personal Care,33,45000,1485000.0,Surabaya,Cash\nT0204,2024-10-01,Tolako Minuman Herbal,Health,86,8500,731000.0,Bandung,Card\nT0205,2024-10-01,Beras Maknyuss 5kg,Groceries,76,65000,4940000.0,Medan,Cash\nT0206,2024-10-06,Sedaap Soto,Instant Noodles,86,2800,,Jakarta,Cash\nT0207,2024-10-04,Sedaap Soto,Instant Noodles,79,2800,221200.0,Medan,Card\nT0208,2024-10-01,Indomilk UHT 1L,Drinks,64,15000,960000.0,Medan,Card\nT0209,2024-10-05,Pantene Shampoo 1L,Personal Care,22,45000,990000.0,Surabaya,Card\nT0210,2024-10-02,SilverQueen Milk Chocolate,Snacks,46,12000,552000.0,Medan,Card\nT0211,2024-10-02,Indomie Goreng,Instant Noodles,83,3000,249000.0,Jakarta,Card\nT0212,2024-10-06,ABC Kecap Manis 620ml,Groceries,62,18000,1116000.0,Bandung,Card\nT0213,2024-10-04,Sampoerna Mild 16,Smokes,64,30000,1920000.0,Surabaya,Card\nT0214,2024-10-05,Sampoerna Mild 16,Smokes,N/A,30000,2130000.0,Medan,Card\nT0215,2024-10-02,Frisian Flag Susu Kental Manis,Groceries,27,10000,270000.0,Jakarta,Cash\nT0216,2024-10-03,Tolak Angin,Health,22,7000,154000.0,Medan,Card\nT0217,2024-10-05,Aqua 600ml,Drinks,30,4000,120000.0,Jakarta,Cash\nT0218,2024-10-05,Sedaap Soto,Instant Noodles,65,2800,182000.0,Surabaya,Cash\nT0219,2024-10-04,Frisian Flag Susu Kental Manis,Groceries,61,10000,610000.0,Surabaya,Cash\nT0220,2024-10-02,Nabati Wafer,Snacks,66,5000,,Surabaya,Cash\nT0221,2024-10-05,Indomilk UHT 1L,Drinks,99,15000,1485000.0,Bandung,Cash\nT0222,2024-10-06,Tolak Angin,Health,21,7000,147000.0,Medan,Card\nT0223,2024-10-06,Beras Maknyuss 5kg,Groceries,76,65000,,Jakarta,Cash\nT0224,2024-10-02,Sampoerna Mild 16,Smokes,84,30000,2520000.0,Surabaya,Cash\nT0225,2024-10-06,Frisian Flag Susu Kental Manis,Groceries,83,10000,,Bandung,Card\nT0226,2024-10-03,Indomilk UHT 1L,Drinks,47,15000,705000.0,Jakarta,Card\nT0227,2024-10-04,Pantene Shampoo 1L,Personal Care,42,45000,1890000.0,Medan,Card\nT0228,2024-10-06,Tolako Minuman Herbal,Health,97,8500,824500.0,Jakarta,Card\nT0229,2024-10-06,Lifebuoy Body Wash,Personal Care,96,25000,2400000.0,Surabaya,Card\nT0230,2024-10-03,Indomie Goreng,Instant Noodles,99,3000,297000.0,Bandung,Card\nT0231,2024-10-04,ABC Kecap Manis 620ml,Groceries,19,18000,342000.0,Bandung,Card\nT0232,2024-10-05,Pantene Shampoo 1L,Personal Care,44,45000,1980000.0,Bandung,Card\nT0233,2024-10-04,Lifebuoy Body Wash,Personal Care,43,25000,1075000.0,Bandung,Cash\nT0234,2024-10-01,Rexona Deodorant,Personal Care,25,20000,500000.0,Medan,Cash\nT0235,2024-10-02,Aqua 600ml,Drinks,71,4000,284000.0,Surabaya,Card\nT0236,2024-10-02,Pantene Shampoo 1L,Personal Care,45,45000,2025000.0,Surabaya,Card\nT0237,2024-10-01,Aqua 600ml,Drinks,77,4000,308000.0,Medan,Cash\nT0238,2024-10-03,Tolak Angin,Health,68,7000,476000.0,Medan,Card\nT0239,2024-10-01,Beras Maknyuss 5kg,Groceries,58,65000,3770000.0,Surabaya,Card\nT0240,2024-10-05,Sampoerna Mild 16,Smokes,43,30000,1290000.0,Medan,Card\nT0241,2024-10-05,Beras Maknyuss 5kg,Groceries,63,65000,4095000.0,Surabaya,Card\nT0242,2024-10-02,Tolak Angin,Health,83,7000,581000.0,Bandung,Cash\nT0243,2024-10-05,Sampoerna Mild 16,Smokes,65,30000,1950000.0,Bandung,Cash\nT0244,2024-10-02,Nabati Wafer,Snacks,N/A,5000,55000.0,Medan,Cash\nT0245,2024-10-01,Indomilk UHT 1L,Drinks,78,15000,1170000.0,Medan,Card\nT0246,2024-10-01,Aqua 600ml,Drinks,60,4000,240000.0,Bandung,Cash\nT0247,2024-10-06,Rexona Deodorant,Personal Care,67,20000,1340000.0,Surabaya,Card\nT0248,2024-10-06,Sari Roti Tawar,Snacks,54,12000,,Jakarta,Card\nT0249,2024-10-01,Beras Maknyuss 5kg,Groceries,83,65000,5395000.0,Bandung,Card\nT0250,2024-10-02,Nabati Wafer,Snacks,67,5000,335000.0,Medan,Card\nT0251,2024-10-01,Tolak Angin,Health,91,7000,637000.0,Surabaya,Card\nT0252,2024-10-01,SilverQueen Milk Chocolate,Snacks,20,12000,240000.0,Bandung,Card\nT0253,2024-10-03,Sari Roti Tawar,Snacks,87,12000,1044000.0,Surabaya,Card\nT0254,2024-10-01,Pantene Shampoo 1L,Personal Care,76,45000,3420000.0,Medan,Cash\nT0255,2024-10-05,Lifebuoy Body Wash,Personal Care,94,25000,2350000.0,Jakarta,Cash\nT0256,2024-10-02,SilverQueen Milk Chocolate,Snacks,70,error,840000.0,Jakarta,Card\nT0257,2024-10-03,Rexona Deodorant,Personal Care,43,20000,860000.0,Jakarta,Card\nT0258,2024-10-06,Milo 1kg,Drinks,66,90000,5940000.0,Bandung,Cash\nT0259,2024-10-04,ABC Kecap Manis 620ml,Groceries,70,18000,1260000.0,Surabaya,Card\nT0260,2024-10-02,Sampoerna Mild 16,Smokes,32,30000,960000.0,Medan,Card\nT0261,2024-10-05,Milo 1kg,Drinks,54,90000,4860000.0,Bandung,Cash\nT0262,2024-10-02,Sari Roti Tawar,Snacks,29,12000,348000.0,Jakarta,Cash\nT0263,2024-10-06,Indomie Goreng,Instant Noodles,98,3000,294000.0,Medan,Card\nT0264,2024-10-05,Milo 1kg,Drinks,86,90000,7740000.0,Jakarta,Card\nT0265,202

In [ ]:
# Membaca dataset
import pandas as pd
df = pd.read_csv("Dataset_sales.csv")

In [ ]:
#Melihat isi dataset
df.head()

,Transaction_ID,Date,Product_Name,Category,Units_Sold,Unit_Price,Total_Revenue,Store_Location,Payment_Method
0,T0001,2024-10-06,Pepsodent Toothpaste,Personal Care,NaN,15000,675000.0,Jakarta,Cash
1,T0002,2024-10-01,ABC Kecap Manis 620ml,Groceries,60.0,18000,1080000.0,Jakarta,Card
2,T0003,2024-10-01,Lifebuoy Body Wash,Personal Care,17.0,25000,425000.0,Medan,Cash
3,T0004,2024-10-06,Milo 1kg,Drinks,95.0,90000,8550000.0,Bandung,Cash
4,T0005,2024-10-03,Indomie Goreng,Instant Noodles,30.0,3000,90000.0,Surabaya,Card

In [ ]:
# Mengubah Unit_Price jadi angka
df['Unit_Price'] = pd.to_numeric(df['Unit_Price'], errors='coerce')

In [ ]:
# Menangani Missing Value
df['Units_Sold'] = df['Units_Sold'].fillna(df['Units_Sold'].median())
df['Unit_Price'] = df['Unit_Price'].fillna(df['Unit_Price'].median())

In [ ]:
# Mengisi Total_Revenue yang kosong
df.loc[df['Total_Revenue'].isna(), 'Total_Revenue'] = \
    df['Units_Sold'] * df['Unit_Price']

In [ ]:
# Mengubah tipe tanggal
df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
# Cek struktur data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  4000 non-null   object
 1   Date            4000 non-null   datetime64[ns]
 2   Product_Name    4000 non-null   object
 3   Category        4000 non-null   object
 4   Units_Sold      4000 non-null   float64
 5   Unit_Price      4000 non-null   float64
 6   Total_Revenue   4000 non-null   float64
 7   Store_Location  4000 non-null   object
 8   Payment_Method  4000 non-null   object
dtypes: datetime64[ns](1), float64(3), object(5)
memory usage: 281.4+ KB

In [ ]:
# Cek data duplikat
df['Transaction_ID'].duplicated().sum()

np.int64(0)

In [ ]:
# Memecah tanggal jadi Tahun, Bulan, Hari
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

In [ ]:
# Perhitungan revenue per toko
store_perf = df.groupby('Store_Location')['Total_Revenue'].sum().reset_index()

In [ ]:
# Agregasi Bulanan
df.groupby(['Year','Month','Store_Location'])['Total_Revenue'].sum()

Year  Month  Store_Location
2024  10     Bandung           1.091441e+09
             Jakarta           1.326678e+09
             Medan             1.106365e+09
             Surabaya          1.150999e+09
Name: Total_Revenue, dtype: float64

# Mendalami Dataset

In [ ]:
# Menampilkan tahun yang tersedia
tahun = df['Date'].dt.year.unique()
print("Tahun yang ada:", sorted(tahun))

Tahun yang ada: [np.int32(2024)]

In [ ]:
# Menampilkan bulan yang tersedia
bulan = df['Date'].dt.month.unique()
print("Bulan yang ada:", sorted(bulan))

Bulan yang ada: [np.int32(10)]

In [ ]:
# Menampilkan hari (tanggal) yang tersedia
hari = df['Date'].dt.day.unique()
print("Hari yang ada:", sorted(hari))

Hari yang ada: [np.int32(1), np.int32(2), np.int32(3), np.int32(4), np.int32(5), np.int32(6)]

In [ ]:
# Lokasi Toko
lokasi_toko = df['Store_Location'].unique()
print("Daftar Lokasi Toko:")
print(lokasi_toko)

Daftar Lokasi Toko:
['Jakarta' 'Medan' 'Bandung' 'Surabaya']

Karena dataset hanya berisi tanggal transaksi bulan 10, tahun 2024, tanggal 1-6. Kami merubah fitur sistem menjadi periode analisis penjualan menjadi harian.

# Fakta

In [ ]:
# Total revenue harian (SEMUA toko)
revenue_harian_global = df.groupby('Date')['Total_Revenue'].sum().reset_index()
revenue_harian_global = revenue_harian_global.sort_values('Date')
print(revenue_harian_global)

        Date  Total_Revenue
0 2024-10-01    761304000.0
1 2024-10-02    734294700.0
2 2024-10-03    774987500.0
3 2024-10-04    804222800.0
4 2024-10-05    764919600.0
5 2024-10-06    835753800.0

In [ ]:
# Total revenue harian PER TOKO
revenue_harian_toko = df.groupby(['Date','Store_Location'])['Total_Revenue'].sum().reset_index()
revenue_harian_toko = revenue_harian_toko.sort_values(['Store_Location','Date'])
print(revenue_harian_toko)

         Date Store_Location  Total_Revenue
0  2024-10-01        Bandung    190071000.0
4  2024-10-02        Bandung    154453500.0
8  2024-10-03        Bandung    183349400.0
12 2024-10-04        Bandung    152705200.0
16 2024-10-05        Bandung    170320800.0
20 2024-10-06        Bandung    240541000.0
1  2024-10-01        Jakarta    208921700.0
5  2024-10-02        Jakarta    191537200.0
9  2024-10-03        Jakarta    210854100.0
13 2024-10-04        Jakarta    260003500.0
17 2024-10-05        Jakarta    240865600.0
21 2024-10-06        Jakarta    214495400.0
2  2024-10-01          Medan    193123800.0
6  2024-10-02          Medan    160458100.0
10 2024-10-03          Medan    173878000.0
14 2024-10-04          Medan    218243000.0
18 2024-10-05          Medan    169226800.0
22 2024-10-06          Medan    191435700.0
3  2024-10-01       Surabaya    169187500.0
7  2024-10-02       Surabaya    227845900.0
11 2024-10-03       Surabaya    206906000.0
15 2024-10-04       Surabaya    173271100.0
19 2024-10-05       Surabaya    184506400.0
23 2024-10-06       Surabaya    189281700.0

In [ ]:
# Perubahan hari ke hari
revenue_harian_global['Prev'] = revenue_harian_global['Total_Revenue'].shift(1)
revenue_harian_global['Perubahan'] = revenue_harian_global['Total_Revenue'] - revenue_harian_global['Prev']

In [ ]:
# Status Tren Harian Global Seluruh Toko
def status_tren(x):
    if pd.isna(x):
        return "Tidak ada data"
    elif x > 0:
        return "Naik"
    elif x < 0:
        return "Turun"
    else:
        return "Stagnan"

revenue_harian_global['Status'] = revenue_harian_global['Perubahan'].apply(status_tren)
print(revenue_harian_global)

        Date  Total_Revenue         Prev   Perubahan          Status
0 2024-10-01    761304000.0          NaN         NaN  Tidak ada data
1 2024-10-02    734294700.0  761304000.0 -27009300.0           Turun
2 2024-10-03    774987500.0  734294700.0  40692800.0            Naik
3 2024-10-04    804222800.0  774987500.0  29235300.0            Naik
4 2024-10-05    764919600.0  804222800.0 -39303200.0           Turun
5 2024-10-06    835753800.0  764919600.0  70834200.0            Naik

In [ ]:
# Status tren (naik / turun / stagnan)
def status_tren(x):
    if pd.isna(x):
        return "Tidak ada data"
    elif x > 0:
        return "Naik"
    elif x < 0:
        return "Turun"
    else:
        return "Stagnan"

revenue_harian_global['Status'] = revenue_harian_global['Perubahan'].apply(status_tren)

print(revenue_harian_global)

        Date  Total_Revenue         Prev   Perubahan          Status
0 2024-10-01    761304000.0          NaN         NaN  Tidak ada data
1 2024-10-02    734294700.0  761304000.0 -27009300.0           Turun
2 2024-10-03    774987500.0  734294700.0  40692800.0            Naik
3 2024-10-04    804222800.0  774987500.0  29235300.0            Naik
4 2024-10-05    764919600.0  804222800.0 -39303200.0           Turun
5 2024-10-06    835753800.0  764919600.0  70834200.0            Naik

In [ ]:
# Hari penjualan terbaik & terburuk
hari_terbaik = revenue_harian_global.loc[revenue_harian_global['Total_Revenue'].idxmax()]
hari_terburuk = revenue_harian_global.loc[revenue_harian_global['Total_Revenue'].idxmin()]

print("Hari terbaik:\n", hari_terbaik)
print("Hari terburuk:\n", hari_terburuk)

Hari terbaik:
 Date             2024-10-06 00:00:00
Total_Revenue            835753800.0
Prev                     764919600.0
Perubahan                 70834200.0
Status                          Naik
Name: 5, dtype: object
Hari terburuk:
 Date             2024-10-02 00:00:00
Total_Revenue            734294700.0
Prev                     761304000.0
Perubahan                -27009300.0
Status                         Turun
Name: 1, dtype: object

In [ ]:
# Kontribusi penjualan tiap toko (%)
total = df['Total_Revenue'].sum()
kontribusi = df.groupby('Store_Location')['Total_Revenue'].sum().reset_index()
kontribusi['Persentase'] = (kontribusi['Total_Revenue'] / total) * 100
print(kontribusi)

  Store_Location  Total_Revenue  Persentase
0        Bandung   1.091441e+09   23.343921
1        Jakarta   1.326678e+09   28.375200
2          Medan   1.106365e+09   23.663128
3       Surabaya   1.150999e+09   24.617751

In [ ]:
# Tren harian PER TOKO (status)
revenue_harian_toko['Prev'] = revenue_harian_toko.groupby('Store_Location')['Total_Revenue'].shift(1)
revenue_harian_toko['Perubahan'] = revenue_harian_toko['Total_Revenue'] - revenue_harian_toko['Prev']
revenue_harian_toko['Status'] = revenue_harian_toko['Perubahan'].apply(status_tren)
output_toko = revenue_harian_toko[['Date', 'Store_Location', 'Total_Revenue', 'Status']]
output_toko = output_toko.sort_values(['Store_Location', 'Date'])
print(output_toko)

         Date Store_Location  Total_Revenue          Status
0  2024-10-01        Bandung    190071000.0  Tidak ada data
4  2024-10-02        Bandung    154453500.0           Turun
8  2024-10-03        Bandung    183349400.0            Naik
12 2024-10-04        Bandung    152705200.0           Turun
16 2024-10-05        Bandung    170320800.0            Naik
20 2024-10-06        Bandung    240541000.0            Naik
1  2024-10-01        Jakarta    208921700.0  Tidak ada data
5  2024-10-02        Jakarta    191537200.0           Turun
9  2024-10-03        Jakarta    210854100.0            Naik
13 2024-10-04        Jakarta    260003500.0            Naik
17 2024-10-05        Jakarta    240865600.0           Turun
21 2024-10-06        Jakarta    214495400.0           Turun
2  2024-10-01          Medan    193123800.0  Tidak ada data
6  2024-10-02          Medan    160458100.0           Turun
10 2024-10-03          Medan    173878000.0            Naik
14 2024-10-04          Medan    218243000.0            Naik
18 2024-10-05          Medan    169226800.0           Turun
22 2024-10-06          Medan    191435700.0            Naik
3  2024-10-01       Surabaya    169187500.0  Tidak ada data
7  2024-10-02       Surabaya    227845900.0            Naik
11 2024-10-03       Surabaya    206906000.0           Turun
15 2024-10-04       Surabaya    173271100.0           Turun
19 2024-10-05       Surabaya    184506400.0            Naik
23 2024-10-06       Surabaya    189281700.0            Naik

# Backward Chaining

Goal dan Rule

*   Apakah tren penjualan harian global naik?

R1:
IF total_penjualan_hari_terakhir > total_penjualan_hari_sebelumnya
THEN tren_penjualan_global = naik

R2:
IF total_penjualan_hari_terakhir < total_penjualan_hari_sebelumnya
THEN tren_penjualan_global = turun

R3:
IF total_penjualan_hari_terakhir = total_penjualan_hari_sebelumnya
THEN tren_penjualan_global = stagnan

*   Apakah tanggal 3 adalah hari dengan penjualan tertinggi?

R4:
IF total_penjualan_tanggal_3 = nilai maksimum dari seluruh tanggal
THEN tanggal_3 = hari_penjualan_tertinggi

*   Apakah Jakarta adalah toko penjualan terendah?

R5:
IF total_penjualan_Jakarta = nilai minimum dari seluruh toko
THEN Jakarta = toko_penjualan_terendah

# Implementasi rule ke Python

In [ ]:
# R1-R3
def cek_tren_global(revenue_harian_global):
    last = revenue_harian_global.iloc[-1]['Total_Revenue']
    prev = revenue_harian_global.iloc[-2]['Total_Revenue']

    if last > prev:
        return "Naik"
    elif last < prev:
        return "Turun"
    else:
        return "Stagnan"

In [ ]:
# R4 (tanggal 3 tertinggi)
def cek_tanggal_tertinggi(revenue_harian_global, tanggal):
    max_val = revenue_harian_global['Total_Revenue'].max()

    nilai_tanggal = revenue_harian_global[
        revenue_harian_global['Date'].dt.day == tanggal
    ]['Total_Revenue'].values[0]

    return nilai_tanggal == max_val

In [ ]:
# R5 (Jakarta terendah)
def cek_toko_terendah(kontribusi_toko):
    min_val = kontribusi_toko['Total_Revenue'].min()

    jakarta = kontribusi_toko[
        kontribusi_toko['Store_Location'] == 'Jakarta'
    ]['Total_Revenue'].values[0]

    return jakarta == min_val

In [ ]:
def backward_chaining(goal, data):

    if goal == "tren_global_naik":
        last = data.iloc[-1]['Total_Revenue']
        prev = data.iloc[-2]['Total_Revenue']
        return last > prev

    elif goal == "tanggal_3_tertinggi":
        max_val = data['Total_Revenue'].max()
        val = data[data['Date'].dt.day == 3]['Total_Revenue'].values[0]
        return val == max_val

    else:
        return "Goal tidak dikenali"

In [ ]:
# Pengujian
print("Apakah tren global naik?")
print(cek_tren_global(revenue_harian_global))

print("\nApakah tanggal 3 tertinggi?")
print(cek_tanggal_tertinggi(revenue_harian_global, 3))

print("\nApakah Jakarta toko terendah?")
print(cek_toko_terendah(store_perf))

Apakah tren global naik?
Naik

Apakah tanggal 3 tertinggi?
False

Apakah Jakarta toko terendah?
False