<a href="https://colab.research.google.com/github/rzangef21/spb-kelompok-2/blob/main/UTS_SBP_Kelompok2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

df = pd.read_csv('/content/Dataset_sales.csv')
df.head()

,Transaction_ID,Date,Product_Name,Category,Units_Sold,Unit_Price,Total_Revenue,Store_Location,Payment_Method
0,T0001,2024-10-06,Pepsodent Toothpaste,Personal Care,NaN,15000,675000.0,Jakarta,Cash
1,T0002,2024-10-01,ABC Kecap Manis 620ml,Groceries,60.0,18000,1080000.0,Jakarta,Card
2,T0003,2024-10-01,Lifebuoy Body Wash,Personal Care,17.0,25000,425000.0,Medan,Cash
3,T0004,2024-10-06,Milo 1kg,Drinks,95.0,90000,8550000.0,Bandung,Cash
4,T0005,2024-10-03,Indomie Goreng,Instant Noodles,30.0,3000,90000.0,Surabaya,Card

In [3]:
df['Unit_Price'] = pd.to_numeric(df['Unit_Price'], errors='coerce')

In [4]:
df['Units_Sold'] = df['Units_Sold'].fillna(df['Units_Sold'].median())
df['Unit_Price'] = df['Unit_Price'].fillna(df['Unit_Price'].median())

In [5]:
df.loc[df['Total_Revenue'].isna(), 'Total_Revenue'] = \
    df['Units_Sold'] * df['Unit_Price']

In [6]:
df['Date'] = pd.to_datetime(df['Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  4000 non-null   object
 1   Date            4000 non-null   datetime64[ns]
 2   Product_Name    4000 non-null   object
 3   Category        4000 non-null   object
 4   Units_Sold      4000 non-null   float64
 5   Unit_Price      4000 non-null   float64
 6   Total_Revenue   4000 non-null   float64
 7   Store_Location  4000 non-null   object
 8   Payment_Method  4000 non-null   object
dtypes: datetime64[ns](1), float64(3), object(5)
memory usage: 281.4+ KB

In [7]:
df['Transaction_ID'].duplicated().sum()

np.int64(0)

In [8]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

In [9]:
df['Sales_Level'] = pd.qcut(df['Total_Revenue'], q=3, labels=['Low','Medium','High'])

In [16]:
store_perf = df.groupby('Store_Location')['Total_Revenue'].sum().reset_index()

In [17]:
best_store = store_perf.loc[store_perf['Total_Revenue'].idxmax()]
worst_store = store_perf.loc[store_perf['Total_Revenue'].idxmin()]

In [18]:
avg = store_perf['Total_Revenue'].mean()

store_perf['Status'] = store_perf['Total_Revenue'].apply(
    lambda x: 'Unggul' if x > avg else ('Rendah' if x < avg else 'Rata-rata')
)

In [19]:
store_perf

  Store_Location  Total_Revenue  Status
0        Bandung   1.091441e+09  Rendah
1        Jakarta   1.326678e+09  Unggul
2          Medan   1.106365e+09  Rendah
3       Surabaya   1.150999e+09  Rendah